name:
  maximum: 50
address:
  maximum: 255
per_page: 10
static_pages:
  per_page: 12
maximum: 150
generate: 122
random: 91
zero: 0
eight: 8
nine: 9
code:
  minimum: 6
percent:
  minimum: 0
  maximum: 100
import:
  minimum: 1

